// types of action
export const CREATE_ITEM = "CREATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const FETCH_ALL_LINKS_REQUEST = "FETCH_ALL_LINKS_REQUEST";
export const FETCH_ALL_LINKS_SUCCESS = "FETCH_ALL_LINKS_SUCCESS";
export const LINKS_FAIL = "LINKS_FAIL";
export const FETCH_LINK_REQUEST = "FETCH_LINK_REQUEST";
export const FETCH_LINK_SUCCESS = "FETCH_LINK_SUCCESS";

export const ADD_NEW_LINK_REQUEST = "ADD_NEW_LINK_REQUEST";
export const ADD_NEW_LINK_SUCCESS = "ADD_NEW_LINK_SUCCESS";

export const DELETE_LINK_REQUEST = "DELETE_LINK_REQUEST";
export const DELETE_LINK_SUCCESS = "DELETE_LINK_SUCCESS";

export const LIKE_LINK_REQUEST = "DELETE_LINK_REQUEST";
export const LIKE_LINK_SUCCESS = "DELETE_LINK_SUCCESS";

export const UNLIKE_LINK_REQUEST = "DELETE_LINK_REQUEST";
export const UNLIKE_LINK_SUCCESS = "DELETE_LINK_SUCCESS";

export const SHOW_DELETE_MODAL = "SHOW_DELETE_MODAL";
export const HIDE_DELETE_MODAL = "HIDE_DELETE_MODAL";